import { ChatOpenAI } from "@langchain/openai";
import { DynamicStructuredTool } from "@langchain/core/tools";
import {
  createDeepAgent,
  CompositeBackend,
  FilesystemBackend,
  StoreBackend,
  type BackendFactory,
} from "deepagents";
import { InMemoryStore, MemorySaver } from "@langchain/langgraph";
import { z } from "zod";
import { DEEP_AGENT_INSTRUCTIONS } from "@/lib/agent/deepagent.prompts";
import type { DeepAgentResult } from "@/lib/agent/deepagent.types";
import {
  buildPromptWithSessionQueryHistory,
  getSessionGraphContextSummary,
  logGeneratedPrompt,
  writeLastPromptMarkdown,
} from "@/lib/agent/deepagent-tools";
import type { ServerConfig } from "@/lib/types";

const checkpointer = new MemorySaver();
const store = new InMemoryStore();

function extractTextContent(content: unknown): string {
  if (typeof content === "string") {
    return content;
  }

  if (Array.isArray(content)) {
    return content
      .map((chunk) => {
        if (typeof chunk === "string") return chunk;
        if (
          chunk &&
          typeof chunk === "object" &&
          "text" in (chunk as Record<string, unknown>)
        ) {
          return String((chunk as Record<string, unknown>).text ?? "");
        }
        return "";
      })
      .join("\n");
  }

  if (content && typeof content === "object") {
    return JSON.stringify(content);
  }

  return "";
}

function parseAgentJson(text: string): DeepAgentResult {
  const trimmed = text.trim();

  try {
    const parsed = JSON.parse(trimmed) as {
      query?: string;
      reasoning?: string;
    };
    if (parsed.query) {
      return {
        query: parsed.query,
        reasoning: parsed.reasoning || "Generated by deepagents",
      };
    }
  } catch {
    // Continue to regex extraction.
  }

  const match = trimmed.match(/\{[\s\S]*\}/);
  if (match) {
    const parsed = JSON.parse(match[0]) as {
      query?: string;
      reasoning?: string;
    };
    if (parsed.query) {
      return {
        query: parsed.query,
        reasoning: parsed.reasoning || "Generated by deepagents",
      };
    }
  }

  throw new Error("Deep agent did not return valid JSON with a query");
}

export async function generateGremlinWithDeepAgent(
  prompt: string,
  server: ServerConfig,
  sessionId: string,
): Promise<DeepAgentResult> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error("OPENAI_API_KEY is required");
  }

  const createCompositeBackend: BackendFactory = (stateAndStore) => {
    const workspaceBackend = new FilesystemBackend({
      rootDir: "./workspace",
      virtualMode: true,
    });

    const persistentBackend = new StoreBackend(stateAndStore, {
      namespace: ["janusgraph-agent", server.id, sessionId, "filesystem"],
    });

    return new CompositeBackend(persistentBackend, {
      "/workspace/": workspaceBackend,
    });
  };

  const model = process.env.OPENAI_MODEL || "gpt-4.1-mini";

  const llm = new ChatOpenAI({
    apiKey,
    model,
    temperature: 0.1,
  });

  const graphContextSummaryPromise = getSessionGraphContextSummary(sessionId);

  const graphContextSummaryTool = new DynamicStructuredTool({
    name: "get_graph_context_summary",
    description:
      "Returns a compact graph context summary with vertex/edge labels, properties, and sample values for this session.",
    schema: z.object({}),
    func: async () => {
      const summary = await graphContextSummaryPromise;
      return JSON.stringify(summary);
    },
  });

  const agent = createDeepAgent({
    model: llm,
    backend: createCompositeBackend,
    checkpointer,
    store,
    tools: [graphContextSummaryTool],
    systemPrompt: DEEP_AGENT_INSTRUCTIONS,
  });

  const promptWithHistory = await buildPromptWithSessionQueryHistory(
    sessionId,
    prompt,
  );
  await graphContextSummaryPromise;

  await logGeneratedPrompt({
    sessionId,
    serverId: server.id,
    model,
    instructions: DEEP_AGENT_INSTRUCTIONS,
    prompt,
    promptWithHistory,
  });

  const result = await agent.invoke(
    {
      messages: [{ role: "user", content: promptWithHistory }],
    },
    {
      configurable: {
        thread_id: `deepagent:${server.id}:${sessionId}`,
      },
    },
  );

  const lastMessage = Array.isArray(result?.messages)
    ? result.messages.at(-1)
    : undefined;
  const content = extractTextContent(
    (lastMessage as { content?: unknown } | undefined)?.content,
  );

  if (!content) {
    await writeLastPromptMarkdown({
      sessionId,
      serverId: server.id,
      model,
      prompt: promptWithHistory,
      agentRawResponse: "",
    });
    throw new Error("Deep agent returned empty content");
  }

  try {
    const parsed = parseAgentJson(content);
    await writeLastPromptMarkdown({
      sessionId,
      serverId: server.id,
      model,
      prompt: promptWithHistory,
      agentRawResponse: content,
      parsedResponse: parsed,
    });
    return parsed;
  } catch (error) {
    await writeLastPromptMarkdown({
      sessionId,
      serverId: server.id,
      model,
      prompt: promptWithHistory,
      agentRawResponse: content,
      parseError:
        error instanceof Error ? error.message : "Unknown parse error",
    });
    throw error;
  }
}
